
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 23.5.0 - arm64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/FindThreads.cmake:99 (CHECK_CXX_SOURCE_COMPILES)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/FindThreads.cmake:163 (_threads_check_libc)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/Qt6Dependencies.cmake:27 (_qt_internal_find_third_party_dependencies)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:136 (include)"
      - "CMakeLists.txt:12 (find_package)"
    checks:
      - "Performing Test CMAKE_HAVE_LIBC_PTHREAD"
    directories:
      source: "/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-oxOZr5"
      binary: "/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-oxOZr5"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/opt/homebrew/opt/llvm/bin/clang-scan-deps"
      CMAKE_CXX_FLAGS: "-Os"
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-s EXPORT_NAME=Something"
      CMAKE_MODULE_PATH: "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/platforms;/Users/admin/repos/emsdk/upstream/emscripten/cmake/Modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "CMAKE_HAVE_LIBC_PTHREAD"
      cached: true
      stdout: |
        Change Dir: '/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-oxOZr5'
        
        Run Build Command(s): /opt/homebrew/bin/ninja -v cmTC_ae440
        [1/2] /Users/admin/repos/emsdk/upstream/emscripten/em++ -DCMAKE_HAVE_LIBC_PTHREAD  -Os  -std=gnu++17 -MD -MT CMakeFiles/cmTC_ae440.dir/src.cxx.o -MF CMakeFiles/cmTC_ae440.dir/src.cxx.o.d -o CMakeFiles/cmTC_ae440.dir/src.cxx.o -c /Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-oxOZr5/src.cxx
        [2/2] : && /Users/admin/repos/emsdk/upstream/emscripten/em++ -Os -s EXPORT_NAME=Something CMakeFiles/cmTC_ae440.dir/src.cxx.o -o cmTC_ae440.js   && :
        cache:INFO: generating system asset: symbol_lists/a911264f9c02533f6bc5f928959161bd9aa9160c.json... (this will be cached in "/Users/admin/repos/emsdk/upstream/emscripten/cache/symbol_lists/a911264f9c02533f6bc5f928959161bd9aa9160c.json" for subsequent builds)
        cache:INFO:  - ok
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/FindWrapAtomic.cmake:36 (check_cxx_source_compiles)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:142 (find_dependency)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Widgets/Qt6WidgetsDependencies.cmake:43 (_qt_internal_find_qt_dependencies)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake:43 (include)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:181 (find_package)"
      - "CMakeLists.txt:12 (find_package)"
    checks:
      - "Performing Test HAVE_STDATOMIC"
    directories:
      source: "/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-ZqT53t"
      binary: "/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-ZqT53t"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/opt/homebrew/opt/llvm/bin/clang-scan-deps"
      CMAKE_CXX_FLAGS: "-Os"
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-s EXPORT_NAME=Something"
      CMAKE_MODULE_PATH: "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/platforms;/Users/admin/repos/emsdk/upstream/emscripten/cmake/Modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_STDATOMIC"
      cached: true
      stdout: |
        Change Dir: '/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-ZqT53t'
        
        Run Build Command(s): /opt/homebrew/bin/ninja -v cmTC_362b5
        [1/2] /Users/admin/repos/emsdk/upstream/emscripten/em++ -DHAVE_STDATOMIC  -Os  -std=gnu++17 -MD -MT CMakeFiles/cmTC_362b5.dir/src.cxx.o -MF CMakeFiles/cmTC_362b5.dir/src.cxx.o.d -o CMakeFiles/cmTC_362b5.dir/src.cxx.o -c /Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-ZqT53t/src.cxx
        [2/2] : && /Users/admin/repos/emsdk/upstream/emscripten/em++ -Os -s EXPORT_NAME=Something CMakeFiles/cmTC_362b5.dir/src.cxx.o -o cmTC_362b5.js   && :
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/FindWrapRt.cmake:23 (check_cxx_source_compiles)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:142 (find_dependency)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Widgets/Qt6WidgetsDependencies.cmake:43 (_qt_internal_find_qt_dependencies)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake:43 (include)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:181 (find_package)"
      - "CMakeLists.txt:12 (find_package)"
    checks:
      - "Performing Test HAVE_GETTIME"
    directories:
      source: "/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-zU0Q6k"
      binary: "/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-zU0Q6k"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/opt/homebrew/opt/llvm/bin/clang-scan-deps"
      CMAKE_CXX_FLAGS: "-Os"
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-s EXPORT_NAME=Something"
      CMAKE_MODULE_PATH: "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/platforms;/Users/admin/repos/emsdk/upstream/emscripten/cmake/Modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_GETTIME"
      cached: true
      stdout: |
        Change Dir: '/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-zU0Q6k'
        
        Run Build Command(s): /opt/homebrew/bin/ninja -v cmTC_36a41
        [1/2] /Users/admin/repos/emsdk/upstream/emscripten/em++ -DHAVE_GETTIME  -Os  -std=gnu++17 -MD -MT CMakeFiles/cmTC_36a41.dir/src.cxx.o -MF CMakeFiles/cmTC_36a41.dir/src.cxx.o.d -o CMakeFiles/cmTC_36a41.dir/src.cxx.o -c /Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-zU0Q6k/src.cxx
        [2/2] : && /Users/admin/repos/emsdk/upstream/emscripten/em++ -Os -s EXPORT_NAME=Something CMakeFiles/cmTC_36a41.dir/src.cxx.o -o cmTC_36a41.js   && :
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/FindWrapRt.cmake:34 (check_cxx_source_compiles)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:142 (find_dependency)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Widgets/Qt6WidgetsDependencies.cmake:43 (_qt_internal_find_qt_dependencies)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake:43 (include)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:181 (find_package)"
      - "CMakeLists.txt:12 (find_package)"
    checks:
      - "Performing Test HAVE_SHM_OPEN_SHM_UNLINK"
    directories:
      source: "/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-IWPsBi"
      binary: "/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-IWPsBi"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/opt/homebrew/opt/llvm/bin/clang-scan-deps"
      CMAKE_CXX_FLAGS: "-Os"
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-s EXPORT_NAME=Something"
      CMAKE_MODULE_PATH: "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/platforms;/Users/admin/repos/emsdk/upstream/emscripten/cmake/Modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_SHM_OPEN_SHM_UNLINK"
      cached: true
      stdout: |
        Change Dir: '/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-IWPsBi'
        
        Run Build Command(s): /opt/homebrew/bin/ninja -v cmTC_bacc9
        [1/2] /Users/admin/repos/emsdk/upstream/emscripten/em++ -DHAVE_SHM_OPEN_SHM_UNLINK  -Os  -std=gnu++17 -MD -MT CMakeFiles/cmTC_bacc9.dir/src.cxx.o -MF CMakeFiles/cmTC_bacc9.dir/src.cxx.o.d -o CMakeFiles/cmTC_bacc9.dir/src.cxx.o -c /Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-IWPsBi/src.cxx
        [2/2] : && /Users/admin/repos/emsdk/upstream/emscripten/em++ -Os -s EXPORT_NAME=Something CMakeFiles/cmTC_bacc9.dir/src.cxx.o -o cmTC_bacc9.js   && :
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules/FindEGL.cmake:127 (check_cxx_source_compiles)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Gui/Qt6GuiDependencies.cmake:39 (_qt_internal_find_third_party_dependencies)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Gui/Qt6GuiConfig.cmake:43 (include)"
      - "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:142 (find_dependency)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Widgets/Qt6WidgetsDependencies.cmake:43 (_qt_internal_find_qt_dependencies)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake:43 (include)"
      - "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:181 (find_package)"
      - "CMakeLists.txt:12 (find_package)"
    checks:
      - "Performing Test HAVE_EGL"
    directories:
      source: "/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-XwPsQh"
      binary: "/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-XwPsQh"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/opt/homebrew/opt/llvm/bin/clang-scan-deps"
      CMAKE_CXX_FLAGS: "-Os"
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-s EXPORT_NAME=Something"
      CMAKE_MODULE_PATH: "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/platforms;/Users/admin/repos/emsdk/upstream/emscripten/cmake/Modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_EGL"
      cached: true
      stdout: |
        Change Dir: '/Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-XwPsQh'
        
        Run Build Command(s): /opt/homebrew/bin/ninja -v cmTC_e87f7
        [1/2] /Users/admin/repos/emsdk/upstream/emscripten/em++ -DHAVE_EGL  -Os  -std=gnu++17 -MD -MT CMakeFiles/cmTC_e87f7.dir/src.cxx.o -MF CMakeFiles/cmTC_e87f7.dir/src.cxx.o.d -o CMakeFiles/cmTC_e87f7.dir/src.cxx.o -c /Users/admin/repos/qtbuild2/CMakeFiles/CMakeScratch/TryCompile-XwPsQh/src.cxx
        [2/2] : && /Users/admin/repos/emsdk/upstream/emscripten/em++ -Os -s EXPORT_NAME=Something CMakeFiles/cmTC_e87f7.dir/src.cxx.o -o cmTC_e87f7.js   && :
        
      exitCode: 0
...
