# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/Users/admin/repos/maplibre-native-qt/examples/widgets;/Users/admin/repos/qtbuild2")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "QMapLibreExampleWidgets built using CMake")
set(CPACK_GENERATOR "TBZ2")
set(CPACK_INNOSETUP_ARCHITECTURE "x86")
set(CPACK_INSTALL_CMAKE_PROJECTS "/Users/admin/repos/qtbuild2;QMapLibreExampleWidgets;ALL;/")
set(CPACK_INSTALL_PREFIX "/Users/admin/repos/emsdk/upstream/emscripten/cache/sysroot")
set(CPACK_MODULE_PATH "/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/platforms;/Users/admin/repos/emsdk/upstream/emscripten/cmake/Modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/admin/Qt/6.8.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin")
set(CPACK_NSIS_DISPLAY_NAME "QMapLibreExampleWidgets 1.0.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "QMapLibreExampleWidgets 1.0.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/opt/homebrew/opt/llvm/bin/llvm-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/opt/homebrew/opt/llvm/bin/llvm-objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/admin/repos/qtbuild2/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "QMapLibreExampleWidgets built using CMake")
set(CPACK_PACKAGE_FILE_NAME "QMapLibreExampleWidgets-1.0.0-Emscripten")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "QMapLibreExampleWidgets 1.0.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "QMapLibreExampleWidgets 1.0.0")
set(CPACK_PACKAGE_NAME "QMapLibreExampleWidgets")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/opt/homebrew/opt/llvm/bin/llvm-readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/Users/admin/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.29/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/admin/repos/qtbuild2/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Emscripten")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Emscripten")
set(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/admin/repos/qtbuild2/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
